version: '3.8'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    volumes:
      - D:/BrovkoLabs/MVC-Store/sql_data:/var/opt/mssql/data
    ports:
      - "1433:1433"

  web:
    build: ./WebUI
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - backend
      - db

  backend:
    build: ./Domain
    container_name: backend
    ports:
      - "8081:80"


volumes:
  db_data: {}

